a="HELLO"
b=""" GOOD EVENING EVERYONE,
  HAVE A LOOK TO THIS PROGRAM,ONLY
  FOR PRACTICE PURPOSE"""
c='''PYTHON IS A HIGH LEVEL LANGUAGE
   HAS SIMPLE SYNTAX,SIMILAR TO ENGLISH &
   MODIFYING FILE'''

print(a.lower())
print(b.lower())
print(c.lower())
